// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthCallbackData, AuthCallbackErrors, AuthCallbackResponses, AuthGetAuthUrlData, AuthGetAuthUrlErrors, AuthGetAuthUrlResponses, AuthLogoutData, AuthLogoutResponses, AuthMeData, AuthMeResponses, CheckoutRepoRefData, CheckoutRepoRefErrors, CheckoutRepoRefResponses, DeployRepoData, DeployRepoErrors, DeployRepoResponses, FetchRepoData, FetchRepoErrors, FetchRepoResponses, GetAllDeployedReposTreeData, GetAllDeployedReposTreeResponses, GetAllReposTreeData, GetAllReposTreeResponses, GetCurrentDeploymentInfoData, GetCurrentDeploymentInfoErrors, GetCurrentDeploymentInfoResponses, GetDeployedRepoFileData, GetDeployedRepoFileErrors, GetDeployedRepoFileResponses, GetDeployedRepoTreeData, GetDeployedRepoTreeErrors, GetDeployedRepoTreeResponses, GetStagingRepoTreeData, GetStagingRepoTreeErrors, GetStagingRepoTreeResponses, HealthCheckData, HealthCheckResponses, ListDeployedReposData, ListDeployedReposResponses, ListRepoRefsData, ListRepoRefsErrors, ListRepoRefsResponses, ListReposData, ListReposResponses, RegisterRepoData, RegisterRepoErrors, RegisterRepoResponses, RootInfoData, RootInfoResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authorize
 */
export const authGetAuthUrl = <ThrowOnError extends boolean = true>(options: Options<AuthGetAuthUrlData, ThrowOnError>) => (options.client ?? client).get<AuthGetAuthUrlResponses, AuthGetAuthUrlErrors, ThrowOnError>({ url: '/api/v1/auth/{provider}/authorize', ...options });

/**
 * Oauth Callback
 */
export const authCallback = <ThrowOnError extends boolean = true>(options: Options<AuthCallbackData, ThrowOnError>) => (options.client ?? client).post<AuthCallbackResponses, AuthCallbackErrors, ThrowOnError>({
    url: '/api/v1/auth/callback',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Me
 */
export const authMe = <ThrowOnError extends boolean = true>(options?: Options<AuthMeData, ThrowOnError>) => (options?.client ?? client).get<AuthMeResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/me', ...options });

/**
 * Logout
 */
export const authLogout = <ThrowOnError extends boolean = true>(options?: Options<AuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * List Repositories
 */
export const listRepos = <ThrowOnError extends boolean = true>(options?: Options<ListReposData, ThrowOnError>) => (options?.client ?? client).get<ListReposResponses, unknown, ThrowOnError>({ url: '/api/v1/repos/staging/', ...options });

/**
 * Get All Repos Tree
 */
export const getAllReposTree = <ThrowOnError extends boolean = true>(options?: Options<GetAllReposTreeData, ThrowOnError>) => (options?.client ?? client).get<GetAllReposTreeResponses, unknown, ThrowOnError>({ url: '/api/v1/repos/staging/tree', ...options });

/**
 * Register Repository
 *
 * Register a Git repository and create a clone
 */
export const registerRepo = <ThrowOnError extends boolean = true>(options: Options<RegisterRepoData, ThrowOnError>) => (options.client ?? client).post<RegisterRepoResponses, RegisterRepoErrors, ThrowOnError>({
    url: '/api/v1/repos/staging/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Repository Refs
 */
export const listRepoRefs = <ThrowOnError extends boolean = true>(options: Options<ListRepoRefsData, ThrowOnError>) => (options.client ?? client).get<ListRepoRefsResponses, ListRepoRefsErrors, ThrowOnError>({ url: '/api/v1/repos/staging/{repo_id}/refs', ...options });

/**
 * Update Repo
 *
 * Fetch new tags/commits from remote without deploying
 */
export const fetchRepo = <ThrowOnError extends boolean = true>(options: Options<FetchRepoData, ThrowOnError>) => (options.client ?? client).post<FetchRepoResponses, FetchRepoErrors, ThrowOnError>({ url: '/api/v1/repos/staging/{repo_id}/fetch', ...options });

/**
 * Deploy Repo
 *
 * Deploy a selected tag or commit to make it available for users
 */
export const deployRepo = <ThrowOnError extends boolean = true>(options: Options<DeployRepoData, ThrowOnError>) => (options.client ?? client).post<DeployRepoResponses, DeployRepoErrors, ThrowOnError>({
    url: '/api/v1/repos/staging/{repo_id}/deploy',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Checkout Repo Ref
 *
 * Checkout a specific ref in the staging repo
 */
export const checkoutRepoRef = <ThrowOnError extends boolean = true>(options: Options<CheckoutRepoRefData, ThrowOnError>) => (options.client ?? client).get<CheckoutRepoRefResponses, CheckoutRepoRefErrors, ThrowOnError>({ url: '/api/v1/repos/staging/{repo_id}/checkout', ...options });

/**
 * Get Staging Repo Tree
 */
export const getStagingRepoTree = <ThrowOnError extends boolean = true>(options: Options<GetStagingRepoTreeData, ThrowOnError>) => (options.client ?? client).get<GetStagingRepoTreeResponses, GetStagingRepoTreeErrors, ThrowOnError>({ url: '/api/v1/repos/staging/{repo_id}/tree', ...options });

/**
 * List Repositories
 */
export const listDeployedRepos = <ThrowOnError extends boolean = true>(options?: Options<ListDeployedReposData, ThrowOnError>) => (options?.client ?? client).get<ListDeployedReposResponses, unknown, ThrowOnError>({ url: '/api/v1/repos/runtime/', ...options });

/**
 * Get All Repos Tree
 */
export const getAllDeployedReposTree = <ThrowOnError extends boolean = true>(options?: Options<GetAllDeployedReposTreeData, ThrowOnError>) => (options?.client ?? client).get<GetAllDeployedReposTreeResponses, unknown, ThrowOnError>({ url: '/api/v1/repos/runtime/tree', ...options });

/**
 * Get Runtime Repo Tree
 *
 * Return the full tree of the currently deployed snapshot.
 */
export const getDeployedRepoTree = <ThrowOnError extends boolean = true>(options: Options<GetDeployedRepoTreeData, ThrowOnError>) => (options.client ?? client).get<GetDeployedRepoTreeResponses, GetDeployedRepoTreeErrors, ThrowOnError>({ url: '/api/v1/repos/runtime/{repo_id}/tree', ...options });

/**
 * Runtime Get Repo File
 *
 * Return the content of a file from the currently deployed snapshot.
 */
export const getDeployedRepoFile = <ThrowOnError extends boolean = true>(options: Options<GetDeployedRepoFileData, ThrowOnError>) => (options.client ?? client).get<GetDeployedRepoFileResponses, GetDeployedRepoFileErrors, ThrowOnError>({ url: '/api/v1/repos/runtime/{repo_id}/file', ...options });

/**
 * Get Current Deployment Info
 *
 * Return information about the currently deployed snapshot.
 */
export const getCurrentDeploymentInfo = <ThrowOnError extends boolean = true>(options: Options<GetCurrentDeploymentInfoData, ThrowOnError>) => (options.client ?? client).get<GetCurrentDeploymentInfoResponses, GetCurrentDeploymentInfoErrors, ThrowOnError>({ url: '/api/v1/repos/runtime/{repo_id}/info', ...options });

/**
 * Root
 */
export const rootInfo = <ThrowOnError extends boolean = true>(options?: Options<RootInfoData, ThrowOnError>) => (options?.client ?? client).get<RootInfoResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health
 */
export const healthCheck = <ThrowOnError extends boolean = true>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });
