// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AuthProvider
 */
export type AuthProvider = 'microsoft' | 'demo';

/**
 * AuthURL
 */
export type AuthUrl = {
    /**
     * Authorize Url
     */
    authorize_url: string;
};

/**
 * DeployRequest
 */
export type DeployRequest = {
    /**
     * Deployment Version
     */
    deployment_version: string;
};

/**
 * DeploymentInfo
 */
export type DeploymentInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Id
     */
    repo_id: string;
    /**
     * Ref
     */
    ref: string;
    /**
     * Commit Hash
     */
    commit_hash: string;
    /**
     * Deployed At
     */
    deployed_at: string | null;
};

/**
 * FileResponse
 */
export type FileResponse = {
    /**
     * Path
     */
    path: string;
    /**
     * Content
     */
    content: string;
    /**
     * Encoding
     */
    encoding?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status: string;
};

/**
 * OAuthCallbackRequest
 */
export type OAuthCallbackRequest = {
    provider: AuthProvider;
    /**
     * Code
     */
    code?: string | null;
    /**
     * Redirect Uri
     */
    redirect_uri?: string | null;
};

/**
 * RepoCreateRequest
 */
export type RepoCreateRequest = {
    /**
     * Alias
     *
     * Local OPI repository name
     */
    alias: string;
    /**
     * Git Url
     *
     * Git repository URL
     */
    git_url: string;
};

/**
 * RepoInfo
 */
export type RepoInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Alias
     */
    alias: string;
    /**
     * Git Url
     */
    git_url: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Refs
     */
    refs: Array<string>;
    /**
     * Current Deployment
     */
    current_deployment?: string | null;
    /**
     * Deployed Ref
     */
    deployed_ref?: string | null;
    /**
     * Deployed At
     */
    deployed_at?: string | null;
};

/**
 * RepoRef
 */
export type RepoRef = {
    /**
     * Ref
     */
    ref: string;
};

/**
 * RepoTreeInfo
 */
export type RepoTreeInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Alias
     */
    alias: string;
    /**
     * Git Url
     */
    git_url: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Refs
     */
    refs: Array<string>;
    /**
     * Current Deployment
     */
    current_deployment?: string | null;
    /**
     * Deployed Ref
     */
    deployed_ref?: string | null;
    /**
     * Deployed At
     */
    deployed_at?: string | null;
    /**
     * Tree
     */
    tree: Array<TreeNode>;
};

/**
 * RootInfo
 */
export type RootInfo = {
    /**
     * Service
     */
    service: string;
    /**
     * Version
     */
    version: string;
};

/**
 * TreeNode
 */
export type TreeNode = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Children
     */
    children?: Array<TreeNode> | null;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string | null;
    provider: AuthProvider;
    /**
     * Provider Id
     */
    provider_id: string;
    role?: UserRole;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * UserRole
 */
export type UserRole = 'developer' | 'operator';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AuthGetAuthUrlData = {
    body?: never;
    path: {
        provider: AuthProvider;
    };
    query?: {
        /**
         * Demo Profile
         */
        demo_profile?: UserRole | null;
    };
    url: '/api/v1/auth/{provider}/authorize';
};

export type AuthGetAuthUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthGetAuthUrlError = AuthGetAuthUrlErrors[keyof AuthGetAuthUrlErrors];

export type AuthGetAuthUrlResponses = {
    /**
     * Successful Response
     */
    200: AuthUrl;
};

export type AuthGetAuthUrlResponse = AuthGetAuthUrlResponses[keyof AuthGetAuthUrlResponses];

export type AuthCallbackData = {
    body: OAuthCallbackRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/callback';
};

export type AuthCallbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthCallbackError = AuthCallbackErrors[keyof AuthCallbackErrors];

export type AuthCallbackResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type AuthCallbackResponse = AuthCallbackResponses[keyof AuthCallbackResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthMeResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListReposData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repos/staging/';
};

export type ListReposResponses = {
    /**
     * Response Listrepos
     *
     * Successful Response
     */
    200: Array<RepoInfo>;
};

export type ListReposResponse = ListReposResponses[keyof ListReposResponses];

export type GetAllReposTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repos/staging/tree';
};

export type GetAllReposTreeResponses = {
    /**
     * Response Getallrepostree
     *
     * Successful Response
     */
    200: Array<RepoTreeInfo>;
};

export type GetAllReposTreeResponse = GetAllReposTreeResponses[keyof GetAllReposTreeResponses];

export type RegisterRepoData = {
    body: RepoCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/repos/staging/register';
};

export type RegisterRepoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRepoError = RegisterRepoErrors[keyof RegisterRepoErrors];

export type RegisterRepoResponses = {
    /**
     * Successful Response
     */
    200: RepoInfo;
};

export type RegisterRepoResponse = RegisterRepoResponses[keyof RegisterRepoResponses];

export type ListRepoRefsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repos/staging/{repo_id}/refs';
};

export type ListRepoRefsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRepoRefsError = ListRepoRefsErrors[keyof ListRepoRefsErrors];

export type ListRepoRefsResponses = {
    /**
     * Response Listreporefs
     *
     * Successful Response
     */
    200: Array<string>;
};

export type ListRepoRefsResponse = ListRepoRefsResponses[keyof ListRepoRefsResponses];

export type FetchRepoData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repos/staging/{repo_id}/fetch';
};

export type FetchRepoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FetchRepoError = FetchRepoErrors[keyof FetchRepoErrors];

export type FetchRepoResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeployRepoData = {
    body: DeployRequest;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repos/staging/{repo_id}/deploy';
};

export type DeployRepoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeployRepoError = DeployRepoErrors[keyof DeployRepoErrors];

export type DeployRepoResponses = {
    /**
     * Successful Response
     */
    200: DeploymentInfo;
};

export type DeployRepoResponse = DeployRepoResponses[keyof DeployRepoResponses];

export type CheckoutRepoRefData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query: {
        /**
         * Ref
         */
        ref: string;
    };
    url: '/api/v1/repos/staging/{repo_id}/checkout';
};

export type CheckoutRepoRefErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutRepoRefError = CheckoutRepoRefErrors[keyof CheckoutRepoRefErrors];

export type CheckoutRepoRefResponses = {
    /**
     * Successful Response
     */
    200: RepoRef;
};

export type CheckoutRepoRefResponse = CheckoutRepoRefResponses[keyof CheckoutRepoRefResponses];

export type GetStagingRepoTreeData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repos/staging/{repo_id}/tree';
};

export type GetStagingRepoTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStagingRepoTreeError = GetStagingRepoTreeErrors[keyof GetStagingRepoTreeErrors];

export type GetStagingRepoTreeResponses = {
    /**
     * Response Getstagingrepotree
     *
     * Successful Response
     */
    200: Array<TreeNode>;
};

export type GetStagingRepoTreeResponse = GetStagingRepoTreeResponses[keyof GetStagingRepoTreeResponses];

export type ListDeployedReposData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repos/runtime/';
};

export type ListDeployedReposResponses = {
    /**
     * Response Listdeployedrepos
     *
     * Successful Response
     */
    200: Array<RepoInfo>;
};

export type ListDeployedReposResponse = ListDeployedReposResponses[keyof ListDeployedReposResponses];

export type GetAllDeployedReposTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repos/runtime/tree';
};

export type GetAllDeployedReposTreeResponses = {
    /**
     * Response Getalldeployedrepostree
     *
     * Successful Response
     */
    200: Array<RepoTreeInfo>;
};

export type GetAllDeployedReposTreeResponse = GetAllDeployedReposTreeResponses[keyof GetAllDeployedReposTreeResponses];

export type GetDeployedRepoTreeData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repos/runtime/{repo_id}/tree';
};

export type GetDeployedRepoTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDeployedRepoTreeError = GetDeployedRepoTreeErrors[keyof GetDeployedRepoTreeErrors];

export type GetDeployedRepoTreeResponses = {
    /**
     * Response Getdeployedrepotree
     *
     * Successful Response
     */
    200: Array<TreeNode>;
};

export type GetDeployedRepoTreeResponse = GetDeployedRepoTreeResponses[keyof GetDeployedRepoTreeResponses];

export type GetDeployedRepoFileData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query: {
        /**
         * Path
         *
         * Path to file inside repository
         */
        path: string;
    };
    url: '/api/v1/repos/runtime/{repo_id}/file';
};

export type GetDeployedRepoFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDeployedRepoFileError = GetDeployedRepoFileErrors[keyof GetDeployedRepoFileErrors];

export type GetDeployedRepoFileResponses = {
    /**
     * Successful Response
     */
    200: FileResponse;
};

export type GetDeployedRepoFileResponse = GetDeployedRepoFileResponses[keyof GetDeployedRepoFileResponses];

export type GetCurrentDeploymentInfoData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repos/runtime/{repo_id}/info';
};

export type GetCurrentDeploymentInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCurrentDeploymentInfoError = GetCurrentDeploymentInfoErrors[keyof GetCurrentDeploymentInfoErrors];

export type GetCurrentDeploymentInfoResponses = {
    /**
     * Successful Response
     */
    200: DeploymentInfo;
};

export type GetCurrentDeploymentInfoResponse = GetCurrentDeploymentInfoResponses[keyof GetCurrentDeploymentInfoResponses];

export type RootInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootInfoResponses = {
    /**
     * Successful Response
     */
    200: RootInfo;
};

export type RootInfoResponse = RootInfoResponses[keyof RootInfoResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
